config/routes.rb
Rails.application.routes.draw do
  resources :plots
  resources :housing_projects

end

app/models/app_config.rb
# Application configuration wish Settingslogic
# Ref: https://github.com/settingslogic/settingslogic#usage
class AppConfig < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/housing_project.rb
class HousingProject < ActiveRecord::Base
  has_many :plots

  serialize :gps_coordinates
  serialize :plot_layout_image_dimensions

  def image_map_width
    self.plot_layout_image_dimensions.first
  end

  def image_map_height
    self.plot_layout_image_dimensions.last
  end
end

app/models/plot.rb
class Plot < ActiveRecord::Base
  belongs_to :housing_project
  belongs_to :user

  serialize :image_map_coordinates




  def tree_name
    self.street_address.split(" ")[1].downcase
  end

  def url_friendly_street_address
    self.street_address.gsub(" ", "_").downcase
  end

  def street_name_and_number
    number = self.street_address.split(" ")[0].downcase
    name = self.street_address.split(" ")[1].downcase
    street = self.street_address.split(" ")[2].downcase
    name_and_number = "#{name}_#{street}_#{number}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :plots

  attr_accessor :terms_of_use

  ROLES = {
    # Translation                                   # Database key
    I18n.t("models.user.roles.user")          =>    "user",
    I18n.t("models.user.roles.administrator") =>    "administrator",
  }

  def full_name
    [self.first_name, self.middle_name, self.last_name].compact.reject{|element| element.empty?}.join(" ")
  end

  def admin?
    self.role == ROLES[I18n.t("models.user.roles.administrator")]
  end

  def promote
    self.role = ROLES[I18n.t("models.user.roles.administrator")]
  end

  def demote
    self.role = ROLES[I18n.t("models.user.roles.user")]
  end

  def self.random_role
    ROLES[ROLES.to_a[rand ROLES.size].first]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  unless AppConfig.http_basic_access_mode == "open"
    http_basic_authenticate_with name: AppConfig.http_basic_name, password: AppConfig.http_basic_password unless Rails.env == "test"
  end
end

app/controllers/housing_projects_controller.rb
class HousingProjectsController < ApplicationController
  before_action :set_housing_project, only: [:show, :edit, :update, :destroy]

  # GET /housing_projects
  # GET /housing_projects.json
  def index
    @housing_projects = HousingProject.all
  end

  # GET /housing_projects/1
  # GET /housing_projects/1.json
  def show
  end

  # GET /housing_projects/new
  def new
    @housing_project = HousingProject.new
  end

  # GET /housing_projects/1/edit
  def edit
  end

  # POST /housing_projects
  # POST /housing_projects.json
  def create
    @housing_project = HousingProject.new(housing_project_params)

    respond_to do |format|
      if @housing_project.save
        format.html { redirect_to @housing_project, notice: 'Housing project was successfully created.' }
        format.json { render :show, status: :created, location: @housing_project }
      else
        format.html { render :new }
        format.json { render json: @housing_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /housing_projects/1
  # PATCH/PUT /housing_projects/1.json
  def update
    respond_to do |format|
      if @housing_project.update(housing_project_params)
        format.html { redirect_to @housing_project, notice: 'Housing project was successfully updated.' }
        format.json { render :show, status: :ok, location: @housing_project }
      else
        format.html { render :edit }
        format.json { render json: @housing_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /housing_projects/1
  # DELETE /housing_projects/1.json
  def destroy
    @housing_project.destroy
    respond_to do |format|
      format.html { redirect_to housing_projects_url, notice: 'Housing project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_housing_project
      @housing_project = HousingProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def housing_project_params
      params.require(:housing_project).permit(:cover_image, :gps_coordinates, :name, :plot_layout_image, :plot_layout_image_dimensions, :state, :subdomain, :summary)
    end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :set_plot, only: [:show, :edit, :update, :destroy]

  # GET /plots
  # GET /plots.json
  def index
    @plots = Plot.all
  end

  # GET /plots/1
  # GET /plots/1.json
  def show
  end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit
  end

  # POST /plots
  # POST /plots.json
  def create
    @plot = Plot.new(plot_params)

    respond_to do |format|
      if @plot.save
        format.html { redirect_to @plot, notice: 'Plot was successfully created.' }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1
  # PATCH/PUT /plots/1.json
  def update
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to @plot, notice: 'Plot was successfully updated.' }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1
  # DELETE /plots/1.json
  def destroy
    @plot.destroy
    respond_to do |format|
      format.html { redirect_to plots_url, notice: 'Plot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plot
      @plot = Plot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plot_params
      params.require(:plot).permit(:is_available, :area, :cash_price, :installment_amount, :term_deposit_amount, :total_installments, :housing_project_id, :user_id, :beacon_code, :designation, :image_map_coordinates, :image_map_shape, :state, :street_address, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_id
    controller.controller_name
  end

  def body_class(body_class)
    content_for(:body_class) do
      body_class
    end
  end

  # Ref: https://github.com/kpumuk/meta-tags
  def default_meta_tags
    {
      description: t("application.meta_tags.description"),
      keywords: t("application.meta_tags.keywords"),
      prefix: " ",
      reverse: true,
      site: t("application.name"),
      title: t("application.client.tagline"),
      open_graph: {
        description: t("application.meta_tags.description"),
        image: root_url + asset_path("logos/galaunia_farms_logo-400x400.png"),
        title: t("application.client.tagline"),
        type: :website,
        url: root_url,
      }
    }
  end
end

app/helpers/housing_projects_helper.rb
module HousingProjectsHelper
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/views/application/_favicons.html.erb
<link rel="shortcut icon" href="<%= image_path("favicon.ico") %>" />
<link rel="apple-touch-icon" href="<%= image_path("apple-touch-icon.png") %>" />
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path("apple-touch-icon-72x72.png") %>" />
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path("apple-touch-icon-114x114.png") %>" />

app/views/application/_footer.html.erb
<footer class="footer">
	<div class="container">
		<p>
			&copy; <%= RomanNumerals.to_roman(Time.zone.now.year) %> <%= link_to t("application.name"), root_path, title: t("application.name") %>. <%= t("views.application._footer.copy.website_by") %> <%= link_to t("application.developer.name"), t("application.developer.url"), title: t("views.application._footer.link.title.developer") %>.
		</p>
	</div><!-- /.container -->
</footer><!-- /.footer -->

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t("application.name"), root_path, class: "navbar-brand", title: t("views.application._navigation.link.title.home") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t("views.application._navigation.link.about"), page_path('about'), title: t("views.application._navigation.link.title.about") %></li>
        <li><%= link_to t("views.application._navigation.link.residential_estate"), housing_projects_path, title: t("views.application._navigation.link.title.residential_estate") %></li>
        <li><%= link_to t("views.application._navigation.link.contact"), page_path('contact'), title: t("views.application._navigation.link.title.contact") %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/application/_old_internet_explorer.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/application/_viewport.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/housing_projects/_form.html.erb
<%= form_for(@housing_project) do |f| %>
  <% if @housing_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@housing_project.errors.count, "error") %> prohibited this housing_project from being saved:</h2>

      <ul>
      <% @housing_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cover_image %><br>
    <%= f.text_field :cover_image %>
  </div>
  <div class="field">
    <%= f.label :gps_coordinates %><br>
    <%= f.text_field :gps_coordinates %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :plot_layout_image %><br>
    <%= f.text_field :plot_layout_image %>
  </div>
  <div class="field">
    <%= f.label :plot_layout_image_dimensions %><br>
    <%= f.text_field :plot_layout_image_dimensions %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/housing_projects/edit.html.erb
<h1>Editing Housing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @housing_project %> |
<%= link_to 'Back', housing_projects_path %>

app/views/housing_projects/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <header>
      <h1><%= title t("views.housing_projects.index.title") %></h1>
    </header>
  </div>
</div><!-- /.row -->




<div class="row">
  <div class="col-lg-12">
    <% @housing_projects.each do |housing_project| %>
      <section class="<%= housing_project.subdomain %> plot details">

        <h2><%= housing_project.name %></h2>

        <p><%= housing_project.summary %></p>

        <%= t("views.housing_projects.index.copy.hover_over_html") %>

        <%= image_tag("land_projects/#{housing_project.subdomain}/#{housing_project.plot_layout_image}",  width: "#{housing_project.image_map_width}", height: "#{housing_project.image_map_height}", class: "img-responsive center-block", usemap: "#plot_layout_map_#{ housing_project.id }") %>

        <map name="plot_layout_map_<%= housing_project.id %>">
          <% housing_project.plots.each do |plot| %>
            <% if plot.image_map_coordinates.present? %>
              <area
                shape="<%= plot.image_map_shape %>"
                coords="<%= plot.image_map_coordinates.join(", ") %>"
                data-toggle="modal"
                href="<%= plot_path(plot) %>"
                alt="<%= plot.street_address %>. <%= t("views.housing_projects.index.copy.plot_availability.is_#{plot.is_available}") %>."
                title="<%= plot.street_address %>. <%= t("views.housing_projects.index.copy.plot_availability.is_#{plot.is_available}") %>."
              />
            <% end %>
          <% end %>
        </map>
      </section><!-- /.<%= housing_project.subdomain %> -->
    <% end %>
  </div>
</div><!-- /.row -->




<script type="text/javascript">
  $(document).ready(function(e) {
    $('img[usemap]').rwdImageMaps();
  });
</script>

app/views/housing_projects/new.html.erb
<h1>New Housing Project</h1>

<%= render 'form' %>

<%= link_to 'Back', housing_projects_path %>

app/views/housing_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cover image:</strong>
  <%= @housing_project.cover_image %>
</p>

<p>
  <strong>Gps coordinates:</strong>
  <%= @housing_project.gps_coordinates %>
</p>

<p>
  <strong>Name:</strong>
  <%= @housing_project.name %>
</p>

<p>
  <strong>Plot layout image:</strong>
  <%= @housing_project.plot_layout_image %>
</p>

<p>
  <strong>Plot layout image dimensions:</strong>
  <%= @housing_project.plot_layout_image_dimensions %>
</p>

<p>
  <strong>State:</strong>
  <%= @housing_project.state %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @housing_project.subdomain %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @housing_project.summary %>
</p>

<%= link_to 'Edit', edit_housing_project_path(@housing_project) %> |
<%= link_to 'Back', housing_projects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<%= display_meta_tags(default_meta_tags) %>

		<%= render "viewport" %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<%= render "favicons" %>

		<%= csrf_meta_tags %>

		<%= render "old_internet_explorer" %>

		<%= render "analytics" %>
	</head>
	<body id="<%= body_id %>" class="<%= yield(:body_class).present? ? yield(:body_class) : "page" %>">
		<div class="container">
			<%= render "navigation" %>

			<%= render "notifications" %>

			<%= yield %>
		</div>

		<%= render "footer" %>

		<%= javascript_include_tag "application" %>
	</body>
</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="col-lg-12">
		<header>
			<h1><%= title t("views.pages.about.title") %></h1>
			<%= t("views.pages.about.copy.tagline_html") %>
		</header>
	</div>
</div><!-- /.row -->




<div class="row">
	<div class="col-lg-8 col-md-8">
		<%= t("views.pages.about.copy.overview_html") %>

		<br />

		<p><%= link_to t("views.pages.about.link.residential_estate"), housing_projects_path, class: "btn btn-primary btn-lg", role: "button", title: t("views.pages.about.link.title.residential_estate") %></p>
	</div>
	<div class="col-lg-4 col-md-4">

	</div>
</div><!-- /.row -->

app/views/pages/contact.html.erb
<h1><%= title t("views.pages.contact.title") %></h1>

app/views/pages/home.html.erb
<% body_class "home" %>


<div class="row">
	<div class="col-lg-4 col-lg-offset-8
							col-md-4 col-md-offset-8
							col-sm-6 col-sm-offset-6">
		<header class="welcome">
			<h1><%= t("views.pages.home.title") %></h1>
			<%= t("views.pages.home.copy.welcome_html") %>

			<br />

			<p>
				<%= link_to t("views.pages.home.link.learn_more"), page_path('about'), class: "btn btn-primary btn-lg", role: "button", title: t("views.pages.home.link.title.learn_more") %>
			</p>
		</header>
	</div>
</div>




<script type="text/javascript">
	$('#pages, body').vegas({
		delay: 10000,
		shuffle: true,
		timer: false,
		transitionDuration: 3000,
		slides: [
			{ src: "<%= asset_path "slides/1.jpg" %>" },
			{ src: "<%= asset_path "slides/2.jpg" %>" },
			{ src: "<%= asset_path "slides/3.jpg" %>" },
			{ src: "<%= asset_path "slides/4.jpg" %>" },
			{ src: "<%= asset_path "slides/5.jpg" %>" },
			{ src: "<%= asset_path "slides/7.jpg" %>" },
			{ src: "<%= asset_path "slides/8.jpg" %>" },
		]
	});
</script>

app/views/plots/_form.html.erb
<%= form_for(@plot) do |f| %>
  <% if @plot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plot.errors.count, "error") %> prohibited this plot from being saved:</h2>

      <ul>
      <% @plot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_available %><br>
    <%= f.check_box :is_available %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :cash_price %><br>
    <%= f.text_field :cash_price %>
  </div>
  <div class="field">
    <%= f.label :installment_amount %><br>
    <%= f.text_field :installment_amount %>
  </div>
  <div class="field">
    <%= f.label :term_deposit_amount %><br>
    <%= f.text_field :term_deposit_amount %>
  </div>
  <div class="field">
    <%= f.label :total_installments %><br>
    <%= f.text_field :total_installments %>
  </div>
  <div class="field">
    <%= f.label :housing_project_id %><br>
    <%= f.text_field :housing_project_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :beacon_code %><br>
    <%= f.text_field :beacon_code %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :image_map_coordinates %><br>
    <%= f.text_field :image_map_coordinates %>
  </div>
  <div class="field">
    <%= f.label :image_map_shape %><br>
    <%= f.text_field :image_map_shape %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plots/edit.html.erb
<h1>Editing Plot</h1>

<%= render 'form' %>

<%= link_to 'Show', @plot %> |
<%= link_to 'Back', plots_path %>

app/views/plots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plots</h1>

<table>
  <thead>
    <tr>
      <th>Is available</th>
      <th>Area</th>
      <th>Cash price</th>
      <th>Installment amount</th>
      <th>Term deposit amount</th>
      <th>Total installments</th>
      <th>Housing project</th>
      <th>User</th>
      <th>Beacon code</th>
      <th>Designation</th>
      <th>Image map coordinates</th>
      <th>Image map shape</th>
      <th>State</th>
      <th>Street address</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plots.each do |plot| %>
      <tr>
        <td><%= plot.is_available %></td>
        <td><%= plot.area %></td>
        <td><%= plot.cash_price %></td>
        <td><%= plot.installment_amount %></td>
        <td><%= plot.term_deposit_amount %></td>
        <td><%= plot.total_installments %></td>
        <td><%= plot.housing_project %></td>
        <td><%= plot.user %></td>
        <td><%= plot.beacon_code %></td>
        <td><%= plot.designation %></td>
        <td><%= plot.image_map_coordinates %></td>
        <td><%= plot.image_map_shape %></td>
        <td><%= plot.state %></td>
        <td><%= plot.street_address %></td>
        <td><%= plot.description %></td>
        <td><%= link_to 'Show', plot %></td>
        <td><%= link_to 'Edit', edit_plot_path(plot) %></td>
        <td><%= link_to 'Destroy', plot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plot', new_plot_path %>

app/views/plots/new.html.erb
<h1>New Plot</h1>

<%= render 'form' %>

<%= link_to 'Back', plots_path %>

app/views/plots/show.html.erb
<% title t("views.plots.show.title", project_name: @plot.housing_project.name, plot_name: @plot.street_address)  %>




<section id="availability">
  <h1>
    <%= link_to @plot.housing_project.name, housing_projects_path %><br />
    <%= @plot.street_address %>
  </h1>

  <br />

  <p>
    <strong><%= t("views.plots.show.copy.area") %></strong>:
    <%= t("views.plots.show.copy.plot_area", plot_area_in_hectares: number_with_precision(@plot.area, precision: 1), plot_area_in_acres: number_with_precision(@plot.area * 2.47105, precision: 1)) %><br />

    <strong><%= t("views.plots.show.copy.available") %></strong>:
    <%= t("views.plots.show.copy.availability.#{@plot.is_available?}") %>
  </p>
</section><!-- /#availability -->




<br class="section_break">